[font]
size = 12

[font.normal]
family = "CaskaydiaCove NFM"
style = "Regular"

[font.bold]
family = "CaskaydiaCove NFM"
style = "Bold"

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove NFM"
style = "Bold Italic"

[window]
opacity = 0.95
