export EDITOR='nvim'
export VISUAL='nvim'

export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

LFCD="$HOME/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

source ~/.config/bash/aliases.sh

if [ -f "$HOME/Prog/gitstatus/gitstatus.prompt.sh" ]; then
    source "$HOME/Prog/gitstatus/gitstatus.prompt.sh"
fi












# Должно быть в самом конце, чтобы перебивать настройки текущего конфига
CUR_MACH_SETTINGS="$HOME/.config/bash/current_machine_settings.sh"
if [ ! -e "$CUR_MACH_SETTINGS" ]; then
    touch "$CUR_MACH_SETTINGS"
fi
source "$CUR_MACH_SETTINGS"
