export EDITOR='nvim'
export VISUAL='nvim'

export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

LFCD="$HOME/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

# Create ~/.scripts/data/cur_dir.txt if it doesn't exist
# Need for aliases scd, dcd, pcd
if [ ! -e "$HOME/.scripts/data/cur_dir.txt" ]; then
    mkdir -p "$HOME/.scripts/data"
    touch "$HOME/.scripts/data/cur_dir.txt"
fi

# Install gitstatus if it isn't installed
if [ -f "$HOME/.scripts/gitstatus/gitstatus.prompt.sh" ]; then
    source "$HOME/.scripts/gitstatus/gitstatus.prompt.sh"
else
    echo "ERROR: gitstatus isn't installed. Install it with command:"
    echo "git clone --depth=1 https://github.com/romkatv/gitstatus.git ~/.scripts/gitstatus"
fi

export HISTSIZE=5000
export HISTFILESIZE=5000
export HISTTIMEFORMAT="[%Y-%m-%d %T] "

source ~/.config/bash/aliases.sh
source ~/.config/bash/poetry_completion.sh










# Должно быть в самом конце, чтобы перебивать настройки текущего конфига
CUR_MACH_SETTINGS="$HOME/.config/bash/current_machine_settings.sh"
if [ ! -e "$CUR_MACH_SETTINGS" ]; then
    touch "$CUR_MACH_SETTINGS"
fi
source "$CUR_MACH_SETTINGS"
